FROM node:26.5.1-alpine@sha256:233761595746769ebfdb6090f44fc7cdf818ae0ce62d2b37e0367723b9823e36 AS operations
WORKDIR /app
COPY package.json package-lock.json .npmrc ./
RUN npm ci --include=dev && apk add --no-cache postgresql-client
COPY . .
RUN DATABASE_URL=postgresql://build:build@localhost:5432/build npm run db:generate:postgres
ENV NODE_ENV=production
ENV EDULOOP_DATABASE_PROVIDER=postgresql
ENV NEXT_TELEMETRY_DISABLED=1
USER node
CMD ["sh"]
