import type { Metadata } from "next";
import Link from "next/link";
import { PRIVACY_VERSION, publicLegalConfiguration } from "@/lib/legal";

export const metadata: Metadata = { title: "隐私说明" };
export const dynamic = "force-dynamic";

export default function PrivacyPolicyPage() {
  const legal = publicLegalConfiguration();
  return <main id="main-content" className="mx-auto max-w-4xl px-5 pb-20 pt-8 sm:px-8 lg:px-12"><header className="rounded-[32px] border-2 border-ink bg-lime p-7 shadow-[0_8px_0_#242136] sm:p-10"><p className="text-xs font-black uppercase tracking-[.2em] text-violet">Privacy notice · {PRIVACY_VERSION}</p><h1 className="mt-3 font-display text-4xl font-black tracking-tight">EduLoop 隐私说明</h1><p className="mt-3 text-sm font-semibold leading-7 text-ink/70">运营方：{legal.entityName} · 联系邮箱：<a href={`mailto:${legal.contactEmail}`} className="font-black underline">{legal.contactEmail}</a></p></header><div className="mt-8 space-y-7 rounded-[28px] border-2 border-ink/10 bg-white p-6 text-sm font-semibold leading-7 text-muted sm:p-9"><section><h2 className="font-display text-2xl font-black text-ink">1. 适用范围与未成年人边界</h2><p className="mt-3">本说明适用于 EduLoop 公共练习与账号服务。访客练习不创建持久身份，也不保存答题、筛选或进度。持久账号只能由年满 18 岁的学习者，或未成年学习者的父母、法定监护人创建和操作；未成年人不得自行创建账号。学校名册或机构账号不在本公共账号规则内，部署方必须另行完成适用法律要求的身份、监护人同意和保留流程。</p></section><section><h2 className="font-display text-2xl font-black text-ink">2. 我们处理的数据</h2><p className="mt-3">账号数据包括规范化邮箱、可选昵称、可选知识阶段与年级、密码单向哈希、邮箱验证状态、所选社交登录关联、条款与隐私版本及成年学习者或监护人身份声明。学习数据包括练习会话、答案结果、收藏、复习计划、XP、连续学习、徽章、题目反馈和是否打开解析。我们不要求真实姓名，不采集精确位置，不建立公开档案或排行榜。</p></section><section><h2 className="font-display text-2xl font-black text-ink">3. 使用目的</h2><p className="mt-3">数据用于验证账号、同步跨设备进度、提供自适应练习与复习、保护会话安全、回应题目反馈、履行导出和删除请求，以及生成不含直接身份信息的学习循环汇总。我们不出售个人数据，也不使用学习记录投放定向广告。</p></section><section><h2 className="font-display text-2xl font-black text-ink">4. 服务提供商与披露</h2><p className="mt-3">部署所使用的托管与 PostgreSQL 基础设施会代表运营方存储应用数据；Resend 处理验证与密码恢复邮件；你主动选择 Google、Microsoft 或 Facebook 登录时，相应提供商会处理认证数据。运营方应在上线前确认这些处理商、数据区域和合同符合 {legal.jurisdiction}。除提供服务、遵守法律或保护用户与系统安全所必需外，我们不向其他方披露数据。</p></section><section><h2 className="font-display text-2xl font-black text-ink">5. 保留与删除</h2><p className="mt-3">账号和学习数据保留到账号所有者删除学习记录或账号。验证与重置链接分别在 24 小时和 30 分钟后失效，只保存不可逆摘要；摘要会在重新签发、成功使用或删除账号时清除。生产备份按运维规则加密并最长保留 30 天，删除内容可能在备份轮换期间继续存在，但不会恢复到在线账号中。</p></section><section><h2 className="font-display text-2xl font-black text-ink">6. 你的选择与权利</h2><p className="mt-3">登录后可在 <Link href="/privacy" className="font-black text-violet underline">数据与隐私</Link> 连接或移除社交登录方式、导出或删除学习数据、删除完整账号。移除社交登录会删除我们保存的对应提供商凭据；如需撤销提供商侧授权，也应使用该提供商的安全设置。即使尚未接受新版条款，仍可进入该页面行使数据权利。也可通过 {legal.contactEmail} 请求访问、更正、删除、限制处理或提出问题；具体权利以 {legal.jurisdiction} 为准。</p></section><section><h2 className="font-display text-2xl font-black text-ink">7. 安全、跨境与变更</h2><p className="mt-3">我们使用加密会话 Cookie、密码哈希、邮箱验证、可撤销会话、访问控制和最小化日志。互联网服务无法保证绝对安全。运营方必须在上线前披露实际托管区域及任何跨境传输机制。重大变更会发布新版本并要求账号所有者再次确认。</p></section></div><p className="mt-7 text-center text-sm font-semibold text-muted"><Link href="/terms" className="font-black text-violet underline">查看服务条款</Link> · <Link href="/practice" className="font-black text-violet underline">返回访客练习</Link></p></main>;
}
