import type { Metadata } from "next";
import Link from "next/link";
import { publicLegalConfiguration, TERMS_VERSION } from "@/lib/legal";

export const metadata: Metadata = { title: "服务条款" };
export const dynamic = "force-dynamic";

export default function TermsPage() {
  const legal = publicLegalConfiguration();
  return <main id="main-content" className="mx-auto max-w-4xl px-5 pb-20 pt-8 sm:px-8 lg:px-12"><header className="rounded-[32px] border-2 border-ink bg-sky p-7 shadow-[0_8px_0_#242136] sm:p-10"><p className="text-xs font-black uppercase tracking-[.2em] text-violet">Terms of service · {TERMS_VERSION}</p><h1 className="mt-3 font-display text-4xl font-black tracking-tight">EduLoop 服务条款</h1><p className="mt-3 text-sm font-semibold leading-7 text-ink/70">服务提供方：{legal.entityName} · 适用约定：{legal.jurisdiction}</p></header><div className="mt-8 space-y-7 rounded-[28px] border-2 border-ink/10 bg-white p-6 text-sm font-semibold leading-7 text-muted sm:p-9"><section><h2 className="font-display text-2xl font-black text-ink">1. 账号资格与监护责任</h2><p className="mt-3">访客练习无需账号。持久账号只能由年满 18 岁的学习者，或未成年学习者的父母、法定监护人创建和操作。监护人应决定服务是否适合学习者并监督使用；未成年人不得虚假声明成年或自行接受本条款。学校或机构不得在未完成适用身份、授权、同意和数据协议前导入学生账号。</p></section><section><h2 className="font-display text-2xl font-black text-ink">2. 服务性质</h2><p className="mt-3">EduLoop 提供练习题、即时反馈、复习计划和学习进度工具。内容用于辅助学习，不替代学校教学、专业教育评估或考试机构的正式材料。题库可能包含来源差异或错误，用户可提交不含个人信息的题目反馈。</p></section><section><h2 className="font-display text-2xl font-black text-ink">3. 账号安全</h2><p className="mt-3">账号所有者应提供可接收验证邮件的邮箱、保护密码和登录设备，并及时使用密码恢复或联系运营方处理异常。不得共享账号给不受其监督的人、绕过邮箱验证或访问控制，也不得冒充他人或监护人。</p></section><section><h2 className="font-display text-2xl font-black text-ink">4. 可接受使用</h2><p className="mt-3">不得攻击、抓取或干扰服务，不得批量复制题库、上传恶意内容、探测其他账号、规避速率限制，或在题目反馈中提交姓名、联系方式等个人信息。运营方可为保护用户、内容与系统而限制或终止违规访问。</p></section><section><h2 className="font-display text-2xl font-black text-ink">5. 内容与知识产权</h2><p className="mt-3">软件、界面与整理成果的权利归其各自权利人。题目来源和转换记录按仓库数据保留。条款不授予除个人学习所需之外的复制、再发布、商业化或建立竞争题库的权利；法定许可不受影响。</p></section><section><h2 className="font-display text-2xl font-black text-ink">6. 数据与终止</h2><p className="mt-3">数据处理见 <Link href="/privacy-policy" className="font-black text-violet underline">隐私说明</Link>。账号所有者可导出或删除学习数据并删除账号。不接受新版条款时，可以退出并继续使用访客练习，同时仍可行使数据权利。运营方停止服务时应提供合理的数据导出或删除安排。</p></section><section><h2 className="font-display text-2xl font-black text-ink">7. 可用性、责任与变更</h2><p className="mt-3">服务按实际可用状态提供，可能因维护、安全事件或第三方故障中断。在适用法律允许范围内，运营方不保证题目完全无误或服务持续可用，也不排除法律不得排除的责任。重大条款变更会使用新版本并要求账号所有者再次确认。</p></section><section><h2 className="font-display text-2xl font-black text-ink">8. 联系与争议</h2><p className="mt-3">问题、投诉或权利请求请发送至 <a href={`mailto:${legal.contactEmail}`} className="font-black text-violet underline">{legal.contactEmail}</a>。双方应先善意沟通；未解决事项按 {legal.jurisdiction} 及其中不得排除的消费者保护规则处理。</p></section></div><p className="mt-7 text-center text-sm font-semibold text-muted"><Link href="/privacy-policy" className="font-black text-violet underline">查看隐私说明</Link> · <Link href="/practice" className="font-black text-violet underline">返回访客练习</Link></p></main>;
}
